### ISSUE TITLE
Do we have ADFS sample for Angular Version 2

### ISSUE THREAD

**Issue by abhishekhingu** [ahelland/AADGuide-CodeSamples#2]

**Comment by ahelland** [comment]
I based myself on this article when testing out ADFS + Angular way back:
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/single-page-application-with-ad-fs

It has been updated since that, but I have not looked into the details of it. With ADFS 2019 it should be fairly standards compliant so you should be able to make it work with third-party OAuth/OIDC libraries though.
